# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
      branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -PreadWriteToken="${{ secrets.READ_WRITE_ARTIFACTZ_TEST_TOKEN }}" -PreadOnlyToken="${{ secrets.READ_ONLY_ARTIFACTZ_TEST_TOKEN }}" -PwriteOnlyToken="${{ secrets.WRITE_ONLY_ARTIFACTZ_TEST_TOKEN }}"
      env:
        GPG_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
        GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: build/test-results/**/*.xml
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: OWASP Analysis
      run: ./gradlew dependencyCheckPurge dependencyCheckAnalyze
    - name: JaCoCo Test Report
      run: ./gradlew jacocoTestReport
    - name: SonarQube Scan
      uses: monstar-lab-oss/sonarqube-github-action@v1.0.1
      with:
        url: ${{ secrets.SONARQUBE_HOST }}
        token: ${{ secrets.SONARQUBE_TOKEN }}
