# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release tag to create'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew build -PreadWriteToken="${{ secrets.READ_WRITE_ARTIFACTZ_TEST_TOKEN }}" -PreadOnlyToken="${{ secrets.READ_ONLY_ARTIFACTZ_TEST_TOKEN }}" -PwriteOnlyToken="${{ secrets.WRITE_ONLY_ARTIFACTZ_TEST_TOKEN }}"
      env:
        RELEASE_TAG: ${{ github.event.release.tag_name }}
        ARTIFACTZ_TOKEN: ${{ secrets.PRODUCTION_ARTIFACTZ_TOKEN }}
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: build/test-results/**/*.xml
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Publish
      run: ./gradlew jreleaserRelease
      env:
        JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        RELEASE_TAG: ${{ github.event.inputs.tag_name }}
        JRELEASER_GPG_SECRET_KEY: ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
        JRELEASER_GPG_PUBLIC_KEY: ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
        JRELEASER_GPG_PASSPHRASE: ${{ secrets.JRELEASER_GPG_SECRET_KEY_PASSWORD }}
        JRELEASER_BRANCH: master
    - name: JReleaser release output
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jreleaser-release
        path: |
          build/jreleaser/trace.log
          build/jreleaser/output.properties
    - name: Publish Artifact Info
      uses: iktech/publish-artifact-javascript-action@v1.0.0
      with:
        name: artifactz-client
        apiToken: ${{ secrets.ARTIFACTZ_TOKEN }}
        stage: Development
        flow: github
        type: JAR
        groupId: io.iktech
        artifactId: artifactz-client
        version: ${{ github.event.release.tag_name }}